# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Electronics Industrial Automation ML DeepL 
email: ozbeybahadirozan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Digital and analog electronics, AI-enabled embedded systems and software, 
  Industrial automation(PLC) for robotics, 
  EDGE AI, IoT with AI, Machine and Deep Learning
twitter_username: https://x.com/bahadirozbey
github_username: https://github.com/bahadirozbey
linkedin_username: www.linkedin.com/in/bahadir-ozan-ozbey-45a228143
minimal_mistakes_skin: "dark"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Bahadır Ozan Özbey"
  avatar : "/assets/images/profil_resmi.jpg"
  bio    : "I am Bahadır, 31 y/o who is both an electrical-electronics engineer and electronics technician. My origins come from Türkiye. Voyage is a passion"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bahadir-ozan-ozbey-45a228143/?originalSubdomain=ge"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bahadirozbey"  
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/bahadirozbey"
    
    

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/bahadirozbey"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bahadirozbey"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bahadir-ozan-ozbey-45a228143/?originalSubdomain=ge"
      

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
